### ISSUE TITLE
[Document][khochaynhalam] - Create content for vegetarian dishes

### ISSUE THREAD

**Issue by LieuTran287** [khochaynhalam/khochaynhalam.github.io#10]
Dear, @all

Tôi sẽ làm các công việc về nội dung của 4 món ăn có trong trang web.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok em. sửa lại từ ngữ đừng có dùng từ liên quan đến các món mặn nhiều nha em. thịt chẳng hạn

**Comment by nhanntdl** [comment]
deadline trong hôm nay nhé em

**Comment by LieuTran287** [comment]
> ok em. sửa lại từ ngữ đừng có dùng từ liên quan đến các món mặn nhiều nha em. thịt chẳng hạn

Dạ vâng

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

Em đã sửa lại rồi anh ạ. Anh xem lại giúp em nha.
![image](https://user-images.githubusercontent.com/54060154/76964809-e26aad00-6955-11ea-80aa-8890a10f0321.png)


Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok. good job
