### ISSUE TITLE
[Feature][khochaynhalam] - Tạo Fanpage

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#12]
Dear @Vi1309 , 

Tạo giúp anh một fanpage trên facebook để phục vụ cho web kho chay nhà làm nha em

Thanks and Best Regards
TrungNhan

**Comment by Vi1309** [comment]
Dear @nhanntdl 

I will take this work.

Thanks
Vi

**Comment by Vi1309** [comment]
Dear @nhanntdl 

em chỉnh sữa lại fanpage rồi, anh  xem lại giùm em với ạ.

Thanks
Vi

**Comment by nhanntdl** [comment]
ok em. anh sẽ cập nhật thêm các yêu cầu cho fanpage. ở thời điểm hiện tại thì như thế là đủ rồi nè
