### ISSUE TITLE
[Design][khochaynhalam] - Lấy màu của trang web

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#13]
Dear Designer

Em giúp anh lấy màu của trang web để sau này code nhé

Anh đã hướng dẫn trong group chat

Làm ra giúp anh một file power point

Thanks and Best Regards
TrungNhan

**Comment by Vi1309** [comment]
Dear @nhanntdl 

I will take this work.

Thanks
Vi

**Comment by nhanntdl** [comment]
Task này đã được chuyển sang task #17
