### ISSUE TITLE
[Design][khochaynhalam] - Chọn font chữ phù hợp để thực hiện code sau này

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#15]
Dear Designer,

Em giúp anh chọn 1-2 font chữ phù hợp để phục vụ cho việc code web sau này
Yêu cầu chọn font chữ:
1. Phục vụ tốt cho tiếng Việt
2. Dễ nhìn, dễ đọc không bị lỗi font
3. Phù hợp với chủ đề và mục đích kinh doanh của khách hàng là bán đồ ăn chay

Please help me design it.

Thanks and Best Regards
TrungNhan

**Comment by Vi1309** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Vi

**Comment by nhanntdl** [comment]
đã xác định xong và setup
