### ISSUE TITLE
[CODE][khochaynhalam] - Setup các giá trị mặc định ban đầu

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#16]
Dear ...

Giúp anh set up các giá trị mặc định ban đầu cho trang web gồm:

1. font size: 16px
2. font chữ: tham khảo kết quả từ task #15 
3. padding
4. margin
5. màu mặc định: đen
6. gạch chân chữ(trường hợp áp dụng cho liên kết): không gạch chân
7. setup các biến màu để sử dụng (tham khảo: https://www.w3schools.com/css/css3_variables.asp)

- Tạo một nhánh con của nhánh `Source` có tên theo mẫu đặt tên nhánh(tham khảo coding rule)

- Setup tại file `index.css` tại nhánh con vừa tạo.

- Sau khi làm xong commit(bằng tiếng **Anh**), push lên remote, tạo một `merge request` từ nhánh con đang làm vào nhánh `Source`, assign merge request cho anh @nhanntdl.

Please help me do this

Thanks and Best Regards
YourName

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had compeled this work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok em
