### ISSUE TITLE
[Document][khochaynhalam] - list ra một danh sách các màu cho trang web

### ISSUE THREAD

**Issue by Vi1309** [khochaynhalam/khochaynhalam.github.io#17]
Dear, @Vi1309 

List ra một danh sách các màu trong trang web bao gôm: 

- Màu 

- Mã màu

- Tên màu

Please help me to documentation for this

Thanks and Best Regards
Vi

**Comment by nhanntdl** [comment]
ha ha. task anh tạo rồi mà. em nhận rồi em chỉ cần làm thôi mà? @Vi1309

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok em
