### ISSUE TITLE
Task[Tranining] - Training thành viên mới

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#2]
Dear @LieuTran287 

hiện tại anh đang bận. em training cho hai bạn giúp anh về các phần ở [wiki ](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki)thanhhuong nhé!

Thanks
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
Good job..
