### ISSUE TITLE
[CODE][khochaynhalam] - Code phần footer

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#20]
Dear @Huong111 

Em code giúp anh phần footer của trang web nhé

Dựa vào mẫu design của trang wix

Please help me do this

Thanks and Best Regards
TrungNhan

**Comment by Huong111** [comment]
Dear @nhanntdl,

I will take this work.

Thanks,
Huong

**Comment by Huong111** [comment]
Dear @nhanntdl,

I had completed.

Thanks,
Huong

**Comment by nhanntdl** [comment]
Dear @Huong111 

Please add create a pull request for your task

![image](https://user-images.githubusercontent.com/52454131/77281132-d20d5600-6cf8-11ea-98a9-5c4438c42d6c.png)

Thanks and Best Regards
TrungNhan
