### ISSUE TITLE
[CODE][khochaynhalam] - Code thanh điều hướng

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#21]
Dear @Vi1309 

Em code giúp anh phần header thanh điều hướng nhé

Dựa vào design ở trang wix nhé

Please help me do this

Thanks and Best Regards
TrungNhan

**Comment by Vi1309** [comment]
Dear @nhanntdl 

I will take this work.

Thanks
Vi

**Comment by Vi1309** [comment]
Dear @nhanntdl 

I had completed.

Thanks
Vi

**Comment by nhanntdl** [comment]
good job
