### ISSUE TITLE
[CODE][khochaynhalam] - Code thanh điều hướng đến các mạng xã hội khác

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#22]
Dear @LieuTran287 

Em code giúp anh phần điều hướng đến các mạng xã hội nhé

Dựa vào thiết kế trang wix nhé

Please help me do this

Thanks and Best Regards
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.
Please check my work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok em.tốt
