### ISSUE TITLE
[Document][khochaynhalam] - Tạo coding rules

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#23]
Dear @Huong111 

Tạo giúp anh một wiki mô tả coding rules của dự án này em nhé

Please help me to documentation for this

Thanks and Best Regards
TrungNhan

**Comment by Huong111** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Huong

**Comment by Huong111** [comment]
Dear @nhanntdl,

I had completed.
https://docs.google.com/document/d/1Ohn2NfTakj2eaZkigdLwog2obHisMPcRuVLIK3_NcII/edit?usp=sharing

Thanks,
Huong

**Comment by nhanntdl** [comment]
ok em
