### ISSUE TITLE
[BUG][khochaynhalam][#22] - BUG điều hướng các mạng xã hội

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#26]
Dear @LieuTran287 

Anh thấy khoản cách giữa góc phải màn hình và các icon mạng xã hội nó hơi nhiều quá. mất cân bằng. Em canh chỉnh lại cho phù hợp nhé

![image](https://user-images.githubusercontent.com/52454131/77282191-d25b2080-6cfb-11ea-9f43-a61aab3802c5.png)

Khi về màn hình điện thoại. Anh thấy mình nên chuyển các liên kết với mạng xã hội lên ở cùng với thanh điều hướng

![image](https://user-images.githubusercontent.com/52454131/77282382-557c7680-6cfc-11ea-8b1e-55517c0f42ab.png)

Hợp tác với Vi để thiết kế lại cho anh chỗ này nhé

Dựa vào mẫu thiết kế nháp này và thiết kế code lại nhé các em
https://www.figma.com/file/BMgH1CSWMBf6WeaG3Y4eXN/khochaynhalam.com?node-id=343%3A2

Thanks and Best Regards
TrungNhan

****
24/03/2020
****

Dear @LieuTran287 

Em sửa lại icon cho anh thành màu đen luôn nhé
Mã màu là '#222222' nhé em

Thanks
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I'm sorry. I see this task.
I will take this work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
> Dear @nhanntdl ,
> 
> I'm sorry. Now I see this task.
> I will take this work.
> 
> Thanks,
> Lieu

ok

**Comment by nhanntdl** [comment]
Dear @LieuTran287 

Em sửa lại icon cho anh thành màu đen luôn nhé
Mã màu là '#222222' nhé em

Thanks
TrungNhan

**Comment by LieuTran287** [comment]
> Dear @LieuTran287
> 
> Em sửa lại icon cho anh thành màu đen luôn nhé
> Mã màu là '#222222' nhé em
> 
> Thanks
> TrungNhan

Dạ vâng.

**Comment by nhanntdl** [comment]
task xong nha em 

**ngưng commit**
