### ISSUE TITLE
[BUG][khochaynhalam][#21] - Yêu cầu chỉnh sửa thanh điều hướng

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#27]
Dear @Vi1309,

Phần thanh điều hướng khi lên trên phone thì nó bị như ảnh dưới đây
![image](https://user-images.githubusercontent.com/52454131/77288116-b3638b00-6d09-11ea-9f61-36eab3c71229.png)
Nên anh nghĩ em nên làm lại thanh điều hướng dựa theo mẫu nháp của anh theo link: 
https://www.figma.com/file/BMgH1CSWMBf6WeaG3Y4eXN/khochaynhalam.com?node-id=343%3A2

Phần thanh điều hướng khi anh ấn vào mỗi liên kết thì nó chưa có chuyển trang và chưa có đổi màu được là trang đang được chọn.
Tìm cách sửa lỗi em nhé

Kết hợp với Liễu để hoàn thành thanh điều hướng em nhé

Thanks and Best Regards
TrungNhan

****
24/03/2020
****

Dear @Vi1309 

Em chỉnh sửa lại mấy cái link thành kiễu chữ in đậm cho giốn với thiết kế nhé

Thanks 
TrungNhan

**Comment by nhanntdl** [comment]
Có vấn đề gì hỏi chị Hương em nhé

**Comment by Vi1309** [comment]
Dear @nhanntdl 

I will take this work.

Thanks
Vi

**Comment by nhanntdl** [comment]
> Dear @nhanntdl
> 
> I will take this work.
> 
> Thanks
> Vi

ok em. cố gắng hoàn thành sớm nhé

**Comment by nhanntdl** [comment]
Dear @Vi1309 

Em chỉnh sửa lại mấy cái link thành kiễu chữ in đậm cho giốn với thiết kế nhé

Thanks 
TrungNhan

**Comment by nhanntdl** [comment]
task xong nha em
**ngưng commit**
