### ISSUE TITLE
[CODE][khochaynhalam] - Tối ưu hóa code footer

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#30]
Dear @Huong111 

Anh muốn em tối ưu hóa code của phần footer lại cho nó đỡ bị bug

Please help me do this

Thanks and Best Regards
TrungNhan

**Comment by Huong111** [comment]
Dear @nhanntdl,

I had completed.

Thanks,
Huong

**Comment by nhanntdl** [comment]
ok em. làm tốt lắm. anh sẽ review. có vấn đề anh sẽ bắt làm lại
