### ISSUE TITLE
[CODE][khochaynhalam] - Code phần banner cho trang Home

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#35]
Dear Coder

Anh cần em code cho anh phần banner của trang Home

Dựa vào thiết kế 
![image](https://user-images.githubusercontent.com/52454131/77492059-1d973f80-6e72-11ea-9d2b-c443e6ee19cc.png)
https://pocteamnhan.wixsite.com/mysite

Yêu cầu của anh:
1. Banner có chiều cao 100% màn hình, không hơn không kém
2. Banner có chiều rộng bằng 100% màn hình, không hơn không kém
3. Hình ảnh sử dụng phải hài hòa hợp lí
4. Hình ảnh phải có một lớp mặt nạ để tạo sự cách biệt với nội dung
5. Hiệu ứng load nội dung
6. Tạo nhánh con từ nhánh `Source` **mới nhất** để bắt đầu code task này

Please help me do this

Thanks and Best Regards
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
11h hôm nay là deadline của em với task này

**Comment by nhanntdl** [comment]
[sea-kings-master.zip](https://github.com/khochaynhalam/khochaynhalam.github.io/files/4396514/sea-kings-master.zip)

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.
Please check my work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok good good
