### ISSUE TITLE
[CODE][khochaynhalam] - Code trang About

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#36]
Dear Coder

Anh muốn em code giúp trang about của trang web

Dựa theo thiết kế:
![image](https://user-images.githubusercontent.com/52454131/77492882-3c96d100-6e74-11ea-9c89-82bb362077f0.png)
https://pocteamnhan.wixsite.com/mysite/about

Yêu cầu của anh:
1. Nội dung: giới thiệu chung về ăn chay ( có vấn đề về content chủ động liên hệ anh Minh)
2. Phần mấy cây dừa: chưa vội thêm. Đợi thiết kế từ @Vi1309 
3. Hiệu ứng load: em làm giống design nha
4. Chiều cao và chiều rộng của phần này là 100%
5. Hình ảnh hài hòa hợp lí (có thể chụp ảnh mới)
6. Tạo nhánh con từ nhánh `Source` **mới nhất** để bắt đầu code task này

Please help me do this

Thanks and Best Regards
TrungNhan

**Comment by Huong111** [comment]
Dear @nhanntdl,

I will take this work.

Thanks,
Huong

**Comment by Huong111** [comment]
Dear @nhanntdl,

I had completed.

Thanhks,
Huong

**Comment by nhanntdl** [comment]
Dear @LieuTran287 ,

Anh loại @Huong111 khỏi dự án rồi
Nên task này em làm giúp anh nhé

Thanks
TrungNhan

**Comment by Huong111** [comment]
Dear @nhanntdl,

I will take this work.

Thanks,
Huong

**Comment by Huong111** [comment]
Dear @nhanntdl ,

I had completed.

Thanks,
Huong

**Comment by nhanntdl** [comment]
ok em. xong nha
