### ISSUE TITLE
[CODE][khochaynhalam] - Chỉnh sửa liên kết đến mạng xã hội

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#37]
Dear @LieuTran287 

Em thêm vào mạng xã hội các mục như sau:
1. Zalo
2. shoppe
3. tiki
4. lazada
Thông tin các trang kia liệ hệ anh Tuấn để biết nhé em

Sửa lại giúp anh phần liên kết đến facebook nhé em
Link: https://www.facebook.com/khochaynhalam2020/

Please help me do this

Thanks and Best Regards
TrungNhan

**Comment by Vi1309** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed.
Please check my work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
OK em. tốt
