### ISSUE TITLE
[Design][KHOCHAYNHALAM] - Design Logo

### ISSUE THREAD

**Issue by khochaynhalam** [khochaynhalam/khochaynhalam.github.io#4]
Dear @Vi1309 

Anh muốn em giúp anh thiết kế logo cho dự án Khochaynhalam

Yêu cầu :
Thiết kế một logo có độ sáng tạo cao. 
Thiết kế mới, hiện đại, phù hợp với mục đích kinh doanh
Màu sắc tươi sáng
**Sử dụng AI để thiết kế**

Please help me design it.

Thanks and Best Regards
Tuấn

****
09/03/2020
****

Dear @Vi1309

Anh muốn em giúp anh thiết kế logo cho dự án khochaynhalam

Yêu cầu :
**Sử dụng AI để thiết kế**
Em vẽ lại dựa vào cái logo cũ mà anh Minh đã cung cấp:
![image](https://user-images.githubusercontent.com/52454131/76198321-733bdd00-6220-11ea-9b76-3b0cb28cbaab.png)

Thiết kế mẫu mới theo phong cách của ảnh: 
![image](https://user-images.githubusercontent.com/52454131/76198241-4982b600-6220-11ea-81a0-cb44cbc6aec3.png)

Lưu file thiết kế vào: nhánh(branch) Design thư mục Design\logo
Các file cần phải có gồm:
1. logo.ai
2. logo.svg
3. logo.png
4. logo.jpg
5. logo.webp

Please help me design it.

Thanks and Best Regards
TrungNhan

**Comment by nhanntdl** [comment]
Dear @Vi1309

Anh muốn em giúp anh thiết kế logo cho dự án khochaynhalam

Yêu cầu :
**Sử dụng AI để thiết kế**
Em vẽ lại dựa vào cái logo cũ mà anh Minh đã cung cấp:
![image](https://user-images.githubusercontent.com/52454131/76198321-733bdd00-6220-11ea-9b76-3b0cb28cbaab.png)

Thiết kế mẫu mới theo phong cách của ảnh: 
![image](https://user-images.githubusercontent.com/52454131/76198241-4982b600-6220-11ea-81a0-cb44cbc6aec3.png)

Lưu file thiết kế vào: nhánh(branch) Design thư mục Design\logo
Các file cần phải có gồm:
1. logo.ai
2. logo.svg
3. logo.png
4. logo.jpg
5. logo.webp

Please help me design it.

Thanks and Best Regards
TrungNhan

**Comment by Vi1309** [comment]
Dear @nhanntdl 

I will take this work.

Thanks
Vi

**Comment by Vi1309** [comment]
Dear @nhanntdl 

Em vẫn đang thiết kế logo và không có vấn đề gì hết.

Thanks
Vi

**Comment by Vi1309** [comment]
Dear @nhanntdl 

![image](https://user-images.githubusercontent.com/59414684/76438199-4557c380-63ed-11ea-8fd9-638510484ec6.png)
Hôm nay em hoàn thành logo được một nữa, còn bỏ chữ  và cắt nền ra nữa là xong.

Thanks
Vi

**Comment by nhanntdl** [comment]
> Dear @nhanntdl
> 
> ![image](https://user-images.githubusercontent.com/59414684/76438199-4557c380-63ed-11ea-8fd9-638510484ec6.png)
> Hôm nay em hoàn thành logo được một nữa, còn bỏ chữ và cắt nền ra nữa là xong.
> 
> Thanks
> Vi

OK em. em giao lại cho Tuấn review nhé

**Comment by Vi1309** [comment]
Dear @khochaynhalam [tuan]

Anh tuấn ơi em xong cái logo rồi nè, anh xem giúp em ok chưa ạ
![image](https://user-images.githubusercontent.com/59414684/76684215-7974f380-663c-11ea-9032-8d81e2372017.png)

Thanks,
Vi

**Comment by nhanntdl** [comment]
ok rồi nè em

**Comment by nhanntdl** [comment]
thêm đuôi .com chỗ khochaynhalam nha em

**Comment by nhanntdl** [comment]
trong hôm nay sửa rồi push lên git luôn cho anh em nhé @Vi1309

**Comment by Vi1309** [comment]
Dear @nhanntdl 

Em đã sữa logo và đẩy lên git rồi, anh xem lại giùm em với ạ.

 Thanks
  Vi

**Comment by nhanntdl** [comment]
ok. good job
