### ISSUE TITLE
[CODE][khochaynhalam] - Introduction to the site

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#47]
Dear @LieuTran287 

Em làm cho anh phần giới thiệu về trang ở trang home nhé

Please help me do this

Thanks and Best Regards
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.
Please check my work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok good anh đã kiểm tra code và thấy khá ổn áp đó em
em hoàn thành task này
anh sẽ đóng task nhé
