### ISSUE TITLE
[Design][khochaynhalam] - Design Home Page

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#5]
Dear Designer,

Thiết kế lại giúp anh trang `Home page` của dự án khochaynhalam,
Dựa vào thiết kế [này](https://pocteamnhan.wixsite.com/mysite) nhé em

Please help me design it.

Thanks and Best Regards
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @khochaynhalam (Tuấn),

Em làm xong cái design cho Home Page rồi ạ.
Anh kiểm tra giúp em xem như thế [này](https://www.figma.com/proto/BMgH1CSWMBf6WeaG3Y4eXN/khochaynhalam.com?node-id=90%3A2&scaling=scale-down-width) được không ạ.
Anh cho em ý kiến.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl and @khochaynhalam [Tuấn],

Daily today:
- Done: em đã thiết kế xong phần Home Page của trang web.
- Todo: em sẽ thiết kế lại phần Home Page theo yêu cầu của hai anh lúc nãy.
- Problem: cái figma em vẫn chưa biết nhiều về nó để thiết kế 1 trang Home Page ví dụ như: cách chỉnh thanh điều hướng, phần liên hệ đến fb,zalo...

Thanks,
Lieu

**Comment by khochaynhalam** [comment]
Dear @all

Anh note lại cho mấy em những cái cần phải sửa của Home Page dự án **khochaynhalam**

 

> Anh không biết mấy từ chuyên ngành nhưng anh sẽ cố gắng nói sao cho dễ hiểu 
> 
>  nhất

1) Cái hình đầu em phải làm cho tràn ra hết và phải xử lí sao cho khi là nền thì chữ trắng hiển thị rõ và nổi bậc
2) Chỉnh lại kiểu chử cho mấy cái HOME , ABOUT ... có viền, màu trắng font đẹp tí, ( font cũ của em nhìn ốm ốm sao á),di chuyển theo con lăn chuột luôn ( cái logo cũng vậy nha ) chữ KHÔ CHAY NHÀ LÀM em làm font vvip tí :))
3) Hình ảnh chổ giới thiệu sản phẩm vs Anh Minh làm sao cho phù hợp tí, có nền trắng giống trang mẫu á 
4) Hình ảnh chổ các món ăn : chỉnh khô vuông, kích thước và khoảng cách giửa các hình em chỉnh sao cho phù hợp dễ nhìn
5) Cái nền hồng cuối kéo full ngang nha rồi cái nền đen sau thay vì vậy thì em coi chỉnh phần chữ sao nhìn cho đẹp đẹp giống trang mẫu á
6) Mấy cái liên kết ngoài ( face, zalo ..) chỉnh giống mẫu và cũng di chuyển theo lăn chuột nhé

ok vậy thôi đó, mấy em cố găng làm nha

chú ý deadline mới nha, ko vượt quá deadline nửa ngày
Thanks
Tuấn

**Comment by LieuTran287** [comment]
> Dear @ALL
> 
> Anh note lại cho mấy em những cái cần phải sửa của Home Page dự án **khochaynhalam**
> 
> > Anh không biết mấy từ chuyên ngành nhưng anh sẽ cố gắng nói sao cho dễ hiểu
> > nhất
> 
> 1. Cái hình đầu em phải làm cho tràn ra hết và phải xử lí sao cho khi là nền thì chữ trắng hiển thị rõ và nổi bậc
> 2. Chỉnh lại kiểu chử cho mấy cái HOME , ABOUT ... có viền, màu trắng font đẹp tí, ( font cũ của em nhìn ốm ốm sao á),di chuyển theo con lăn chuột luôn ( cái logo cũng vậy nha ) chữ KHÔ CHAY NHÀ LÀM em làm font vvip tí :))
> 3. Hình ảnh chổ giới thiệu sản phẩm vs Anh Minh làm sao cho phù hợp tí, có nền trắng giống trang mẫu á
> 4. Hình ảnh chổ các món ăn : chỉnh khô vuông, kích thước và khoảng cách giửa các hình em chỉnh sao cho phù hợp dễ nhìn
> 5. Cái nền hồng cuối kéo full ngang nha rồi cái nền đen sau thay vì vậy thì em coi chỉnh phần chữ sao nhìn cho đẹp đẹp giống trang mẫu á
> 6. Mấy cái liên kết ngoài ( face, zalo ..) chỉnh giống mẫu và cũng di chuyển theo lăn chuột nhé
> 
> ok vậy thôi đó, mấy em cố găng làm nha
> 
> chú ý deadline mới nha, ko vượt quá deadline nửa ngày
> Thanks
> Tuấn

Dạ vâng

**Comment by LieuTran287** [comment]
Dear @khochaynhalam [Tuấn],

Ngày hôm nay em đã sửa lại cái design Home Page trong [figma](https://www.figma.com/proto/BMgH1CSWMBf6WeaG3Y4eXN/khochaynhalam.com?node-id=136%3A2&scaling=min-zoom).
Công việc của em vẫn chưa hoàn thành, em sẽ tiếp tục vào ngày mai.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
OK em. hoàn thành. tiếp tục với task tiếp theo nhé #8
