### ISSUE TITLE
[CODE][khochaynhalam] - Catering  - "Our Catering"

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#50]
Dear @LieuTran287 

Em code giúp anh phần "Our Catering" của trang Catering nhé. 

Em dựa vào thiết kế này nha:
![image](https://user-images.githubusercontent.com/52454131/77842623-b6092900-71be-11ea-9ed5-57ac1732cc75.png)

Em checkout branch #50 về làm nhé

Please help me do this

Thanks and Best Regards
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.
Please check my work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ngon rồi đó em. để ý lần sau push lên đúng branch giúp anh nhé
