### ISSUE TITLE
[BUG][khochaynhalam][#35] - Sửa lỗi banner trang home

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#51]
Dear @LieuTran287 

Em sửa lại phần banner của trang home lại giúp anh nha
Các lỗi như sau:
1. Phần chữ nó không nằm ở center của banner
![image](https://user-images.githubusercontent.com/52454131/77846331-933b3c80-71df-11ea-8acc-087d9780f41f.png)
Anh muốn phần text nó phải luôn ở trang thái nằm giữa em nhé

2. Màn hình có độ cao thấp thì ảnh bị bóp thấp lại, rất xấu
![image](https://user-images.githubusercontent.com/52454131/77846370-d09fca00-71df-11ea-8acf-296891375e60.png)

Em checkout nhánh #51 để làm nhé

Em sửa lại giúp anh nhé

Thanks
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.
Please check my work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok rồi đó em
