### ISSUE TITLE
[CODE][khochaynhalam] - Completing the catering page code

### ISSUE THREAD

**Issue by LieuTran287** [khochaynhalam/khochaynhalam.github.io#53]
Dear @LieuTran287 ,

Code để hoàn thành giao diện trang CATERING theo trang wix có sẵn.

Please help me do this.

Thanks and Best Regards
Lieu

**Comment by LieuTran287** [comment]
I take this work.

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed.
Please check my work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok em
