### ISSUE TITLE
[CODE][khochaynhalam] - Hoàn thành phần còn lại của trang Home

### ISSUE THREAD

**Issue by LieuTran287** [khochaynhalam/khochaynhalam.github.io#58]
Dear, @LieuTran287 

Hoàn thành phần nội dung còn lại của trang home.

Please help me do this

Thanks and Best Regards
Lieu

**Comment by LieuTran287** [comment]
Dear @LieuTran287 ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I completed this work.
Please check my work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok em anh sẽ check sau
