### ISSUE TITLE
[Research][khochaynhalam] - Phân thích chức năng

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#6]
Dear @Huong111 , 

Tìm hiểu giúp anh trong design [này](https://pocteamnhan.wixsite.com/mysite) sẽ có bao nhiêu chức năng cho cả trang web

Phân tích cần thiết hay không để giữ lại hoặc làm thêm chức năng

Phân tích các cách thực hiện chức năng đó

Tạo một file doc để viết các chức năng và gợi ý cách thực hiện code

Thanks and Best Regards
TrungNhan

**Comment by nhanntdl** [comment]
Dear @Huong111 

Thay đổi yêu cầu của task này

Dựa vào thiết kêd tự wix anh đã cung cấp

Hãy giúp anh làm một file phân tích các chức năng và liệt kê ra tất cả những gì các em cần training để code dự án này

Thank
TrungNhan

**Comment by Huong111** [comment]
Dear @nhanntdl ,

I had completed.
https://docs.google.com/document/d/1fGO6wxLTfbuWbv3QzxIC6gogZ-fkdWfmQF8uATFgJ2s/edit?usp=sharing

Thanks,
Huong

**Comment by nhanntdl** [comment]
ok rồi nha em. nhớ đọc kỹ yêu cầu. làm sao cho nhanh nhất có thể nha
