### ISSUE TITLE
[CODE][khochaynhalam] - code contact page

### ISSUE THREAD

**Issue by Huong111** [khochaynhalam/khochaynhalam.github.io#60]
Dear, @Huong111 

Code contact page.

Please help me do this

Thanks and Best Regards
Huong

**Comment by Huong111** [comment]
Dear @nhanntdl,

I will take this work.

Thanks,
Huong

**Comment by Huong111** [comment]
Dear @nhanntdl,

I had completed.

Thanks,
Huong

**Comment by nhanntdl** [comment]
ok em
