### ISSUE TITLE
[Feature request][khochaynhalam] - Yêu cầu chức năng bản đồ

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#7]
Dear @all,

![image](https://user-images.githubusercontent.com/52454131/76200922-0119c700-6225-11ea-8fdb-5412d739509f.png)

Như ảnh các em thấy ở trên
Chức năng mới mà anh Minh yêu cầu chúng ta làm:

**Describe.**

Anh Minh yêu cầu chức năng mới là hiển thị map cho mỗi cửa hàng có bán sản phẩm của anh Minh

**Solutions**

1. Tab mới hiển thị các thông tin
- Chia các cửa hàng theo các tỉnh thành riêng
- Tên cửa hàng
- Địa chỉ cửa hàng
- Thông tin cơ bản của cửa hàng(mặt hàng cửa hàng đó bán, thông tin giảm giá,... ).
- Map

2. Mỗi một sản phẩm đều có danh sách các cửa hàng bán sản phẩm đó
- Chia các cửa hàng theo các tỉnh thành riêng
- Tên cửa hàng
- Địa chỉ cửa hàng

Giúp anh tìm hiểu, phân tích và thiết kế chức năng này nhé các em

Thanks
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by Huong111** [comment]
Dear @nhanntdl,

I had completed!

Thanks,
Huong

**Comment by nhanntdl** [comment]
ok rồi á em. nhưng nhớ đọc rõ yêu cầu rồi làm nha em
