### ISSUE TITLE
[Design][khochaynhalam] - Design About Page

### ISSUE THREAD

**Issue by khochaynhalam** [khochaynhalam/khochaynhalam.github.io#8]
Dear @ALL

Mấy em giúp anh thiết kế trang About dựa vào thiết kế trên trang wix 
Nhe
Please help me design it.

Thanks and Best Regards
Tuấn

**Comment by LieuTran287** [comment]
Dear @khochaynhalam [Tuan],

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @khochaynhalam [Tuan],

Anh ơi, em design xong cái About Page trên [figma](https://www.figma.com/proto/BMgH1CSWMBf6WeaG3Y4eXN/khochaynhalam.com?node-id=261%3A2&scaling=min-zoom) rồi nha anh.
Anh xem giúp em như thế được không ạ.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok rồi đó em. khi code sẽ khác nhiều. chú ý
